# This is a basic workflow to help you get started with Actions

name: Book Tennis Court

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '55 18 * * *'  # UTC 时间18:55，每天加州时间11:55运行（夏令时）
    # - cron: '55 19 * * *'  # UTC 时间19:55，每天加州时间11:55运行（标准时间）（11 月至次年 3 月）：

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up the environment
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium
          pip install pandas
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Export GOOGLE_APPLICATION_CREDENTIALS
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > "${HOME}/service_account.json"

      # Runs a set of commands using the runners shell
      - name: Run the reservation script
        run: python your_script.py --reservation_date 10/06/2024 --start_time_text 8:00am 8:30am 9:00am --max_attempts 3 --interval_duration 90
          
        env: # Or as an environment variable
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_PASSWORD: ${{ secrets.LT_PASSWORD }}
          CALENDAR_ID: ${{ vars.CALENDAR_ID }}
