# This is a basic workflow to help you get started with Actions

name: Sync Google Calendar

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'  # Runs every hour, at the start of the hour (00:00, 01:00, 02:00, etc.)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up the environment
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium
          pip install pandas
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
          pip install lxml

      - name: Export GOOGLE_APPLICATION_CREDENTIALS
        run:  printf "%s" "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > "${HOME}/service_account.json"

      # Runs a set of commands using the runners shell
      - name: Run the calendar sync script
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS_PATH="${HOME}/service_account.json"  
          python sync_calendar.py
        env: # Or as an environment variable
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_PASSWORD: ${{ secrets.LT_PASSWORD }}
          CALENDAR_ID: ${{ vars.CALENDAR_ID }}
